# Generated by Django 3.2.2 on 2021-05-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0002_pictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='animal/media'),
        ),
    ]
